name: Validate

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    lint-typecheck-test:
        name: Lint, Typecheck, & Test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                python: [3.7, 3.8]
        steps:
        - name: Checkout
          uses: actions/checkout@v2.3.4
        - name: Setup Python ${{ matrix.python }}
          uses: actions/setup-python@v2.2.1
          with:
            python-version: ${{ matrix.python }}
        - name: Install Dependencies
          run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
        - name: Lint with flake8
          run: |
               flake8
        - name: Typecheck with Pytype
          run: pytype cpr_reputation
        - name: Unit Test
          run: pytest test/unit
        - name: Property Test
          run: pytest test/property
